import { useState } from 'react';
import './App.css';
import { Sparkles } from 'lucide-react';
import { UploadSection } from './components/UploadSection';
import { CardPreview } from './components/CardPreview';
import { EmailForm } from './components/EmailForm';
import { generateFestiveMessage } from './services/gemini';
import { sendFestiveEmail } from './services/resend';

function App() {
  const [step, setStep] = useState('upload'); // 'upload' | 'preview'
  const [showEmailForm, setShowEmailForm] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const [image, setImage] = useState(null);
  const [message, setMessage] = useState('');
  const [config, setConfig] = useState({
    gemini: 'AIzaSyD2O_4SblA6GzLeIbVivQ8S1Pnaxv1KADo',
    resend: 're_TxE6ygDr_9NtMqvYhpBhhfxj4HMSkWdLD'
  });

  const [isProcessing, setIsProcessing] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [notification, setNotification] = useState(null);

  const showNotification = (msg, type = 'info') => {
    setNotification({ msg, type });
    setTimeout(() => setNotification(null), 5000);
  };

  const handleUploadAndGenerate = async (file, currentConfig) => {
    // Determine which config to use (passed or state)
    const keys = currentConfig || config;

    setIsProcessing(true);
    setImage(file);
    // If config was passed, update state
    if (currentConfig) setConfig(currentConfig);

    try {
      let msg;

      // DEMO MODE CHECK: If no key provided, use fake data
      if (!keys.gemini) {
        // Fake delay
        await new Promise(resolve => setTimeout(resolve, 1500));
        msg = "✨ Magic of the Season! (Demo Mode: Add API Key to use AI) 🎄";
        showNotification("Demo Mode: Using placeholder text. Add Key for AI!", "info");
      } else {
        msg = await generateFestiveMessage(keys.gemini, file);
      }

      setMessage(msg);
      setStep('preview');
    } catch (error) {
      console.error(error);
      showNotification("Failed to generate message. Check API Key.", "error");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleRegenerate = async () => {
    if (!config.gemini || !image) return;
    setIsProcessing(true);
    try {
      const msg = await generateFestiveMessage(config.gemini, image, "Make it different and creative!");
      setMessage(msg);
    } catch (error) {
      showNotification("Failed to regenerate.", "error");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleSendEmail = async (senderEmail, toEmail, subject) => {
    if (!config.resend) {
      showNotification("Resend API Key required.", "error");
      return;
    }

    setIsSending(true);

    try {
      // Prepare attachment
      const reader = new FileReader();
      reader.onloadend = async () => {
        const base64Content = reader.result.split(',')[1]; // Remove data URL prefix

        // Add sender info to body if available
        const senderInfo = senderEmail ? `<p style="font-size: 12px; color: #777; margin-top: 10px;">Sent by: ${senderEmail}</p>` : '';

        const html = `
          <div style="font-family: sans-serif; color: #333; max-width: 600px; margin: 0 auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
            <div style="background: #d32f2f; padding: 24px; text-align: center;">
               <h1 style="color: white; margin: 0; font-size: 24px;">🎄 A Festive Wish For You!</h1>
            </div>
            
            <div style="padding: 24px;">
               <div style="text-align: center; margin-bottom: 24px;">
                  <img src="cid:festive-card" alt="Festive Card" style="max-width: 100%; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);" />
               </div>

               <p style="font-size: 18px; font-style: italic; color: #555; background: #f9f9f9; padding: 20px; border-left: 4px solid #d32f2f; margin: 0 0 20px 0;">
                 "${message}"
               </p>
               
               ${senderInfo}
            </div>
            
            <div style="text-align: center; padding: 16px; background: #f5f5f5; font-size: 12px; color: #888;">
              <p>Generated by AI Festive Card Creator</p>
            </div>
          </div>
        `;

        const attachments = [{
          filename: 'festive-card.png',
          content: base64Content,
          content_id: 'festive-card' // referencing cid in img src
        }];

        await sendFestiveEmail(config.resend, toEmail, subject, html, attachments, senderEmail);

        // showNotification("Card sent successfully! 🎁", "success");
        setIsSuccess(true);
        // setShowEmailForm(false); // Validated: Don't close, show success view instead
      };
      reader.readAsDataURL(image);

    } catch (error) {
      console.error(error);
      showNotification(`Failed to send: ${error.message}`, "error");
    } finally {
      setIsSending(false);
    }
  };

  return (
    <div className="app-container">
      {notification && (
        <div className={`fixed top-4 right-4 z-[100] px-6 py-3 rounded-lg shadow-lg animate-fade-in ${notification.type === 'error' ? 'bg-red-500/90' : 'bg-green-500/90'
          }`}>
          {notification.msg}
        </div>
      )}

      <header className="app-header animate-fade-in">
        <div className="logo glass-panel" onClick={() => setStep('upload')}>
          <Sparkles className="icon-gold" size={24} />
          <span>FestiveCards</span>
        </div>
      </header>

      <main className="main-content">
        <div className="hero-section animate-fade-in" style={{ animationDelay: '0.1s' }}>
          {step === 'upload' && (
            <>
              <h1 className="hero-title">
                Send <span className="text-gradient-red">Holiday Magic</span><br />
                With <span className="text-gradient-gold">AI</span>
              </h1>
              <p className="hero-subtitle">
                Create personalized Christmas and New Year cards from your photos in seconds.
              </p>
              <UploadSection
                onImageUpload={(file) => handleUploadAndGenerate(file, null)}
                isProcessing={isProcessing}
              />
            </>
          )}

          <CardPreview
            image={image}
            message={message}
            onRegenerate={handleRegenerate}
            onSend={(editedMsg) => {
              setMessage(editedMsg);
              setShowEmailForm(true);
            }}
            isSending={isSending}
          />
        </div>
      </main>

      {showEmailForm && (
        <EmailForm
          onSubmit={handleSendEmail}
          onClose={() => {
            setShowEmailForm(false);
            setIsSuccess(false);
          }}
          isSending={isSending}
          isSuccess={isSuccess}
        />
      )}
    </div>
  );
}

export default App;
